- name: Instalar Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: copy jenkins.conf
  copy:
    src: "jenkins.conf"
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0755
  notify: "restart nginx"

