- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: "/etc/apt/sources.list.d/docker"
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    update_cache: yes
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

# Users
- name: Add user 'azureuser' to 'docker' group
  ansible.builtin.user:
    name: azureuser
    groups: docker
    append: yes

- name: Add user 'jenkins' to 'docker' group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes

# Swarm
- name: Docker Swarm Init
  ansible.builtin.command:
    cmd: docker swarm init