---
- name: Playbook para instalar Jenkins
  hosts: all
  become: true
  become_method: sudo
  vars:
    linux_user: "azureuser"
  roles:
    - common
    - jenkins
    - nginx
    - docker
    #- sonarqube
    - security
