---
- name: Playbook para instalar Jenkins
  hosts: all
  become: yes

  tasks:
    - name: Descargar la clave GPG de Jenkins
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    #- name: Agregar el repositorio de Jenkins
    #  ansible.builtin.command:
    #    cmd: echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list
    #    creates: /etc/apt/sources.list.d/jenkins.list
    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: "/etc/apt/sources.list.d/jenkins"
        state: present

    - name: Actualizar el índice de paquetes
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar fontconfig y OpenJDK 17
      ansible.builtin.apt:
        name:
          - fontconfig
          - openjdk-17-jre
        state: present

    - name: Instalar Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Asegurarse de que Jenkins esté iniciado y habilitado
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started

    # Docker
    # - name: Update apt cache
    #   ansible.builtin.apt:
    #     update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name: 
          - ca-certificates
          - curl
        state: present

    - name: Create directory for apt keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: "/etc/apt/sources.list.d/docker"
        state: present

    - name: Install Docker packages
      ansible.builtin.apt:
        update_cache: yes
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

